---
title: "Análise de commits no Github"
author: "José Benardi de Souza Nunes"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
---

<br>


```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(here)
library(tidyverse)
library(lubridate)
library(timeDate)
library(resample)

theme_set(theme_bw())
```

# Data Overview

```{r, warning=FALSE}
readr::read_csv(here::here("data/github-users-committing-filetypes.csv"),
                      progress = FALSE,
                      col_types = cols(
                        file_extension = col_character(),
                        month_day = col_integer(),
                        the_month = col_integer(),
                        the_year = col_integer(),
                        users = col_integer()
                        )) -> data
data %>% 
  glimpse()
```

## Was the commit made on a weekend ?

```{r}
data %>%
  mutate(isWeekend = timeDate::isWeekend(
    lubridate::ymd(paste(the_year,
                         the_month,
                         month_day)))) -> data
data %>%
  sample_n(10)
```

```{r}
data %>%
  ggplot(aes(isWeekend,
             y=(..count..)/sum(..count..),
             fill = isWeekend)) +
  geom_bar() + 
  labs(y="Frequência Relativa")
```

```{r}
data %>%
  group_by(file_extension, isWeekend) %>%
  summarise(popularity = sum(users)) %>%
  ggplot(aes(x=reorder(file_extension,popularity),
             y = popularity,
             fill=isWeekend)) + 
  geom_bar(stat="identity") + 
  theme(axis.text.x = element_text(angle=60, hjust=1))
```

## Java

```{r}
data %>%
  filter(file_extension == "java") %>%
  ggplot(aes(x="", 
             y=users,
             group=isWeekend, 
             fill=isWeekend)) + 
  geom_boxplot() +
  labs(x="") +
  ggtitle("Java popularity weekday vs weekend")
```

## Python

```{r}
data %>%
  filter(file_extension == "py") %>%
  ggplot(aes(x="", 
             y=users,
             group=isWeekend, 
             fill=isWeekend)) + 
  geom_boxplot() + 
  labs(x="") +
  ggtitle("Python popularity weekday vs weekend")
```

## How they behave on the weekend?

```{r}
data %>%
  filter(isWeekend) %>%
  filter(file_extension %in% c("py","java")) %>%
  ggplot(aes(x=file_extension, 
             y=users,
             group=file_extension, 
             fill=file_extension)) + 
  geom_boxplot() +
  ggtitle("Python vs Java on the weekends")
```

```{r}
data %>%
  filter(file_extension == "java") %>%
  filter(!isWeekend) %>%
  bootstrap(median(users), R = 10000) %>% 
    CI.percentile(probs = c(.025, .975)) -> java.week
data %>%
  filter(file_extension == "java") %>%
  filter(isWeekend) %>%
  bootstrap(median(users), R = 10000) %>% 
    CI.percentile(probs = c(.025, .975)) -> java.weekend

cat(paste("Java on week days:\n"))
java.week
cat(paste("\n\nJava on weekend days:\n"))
java.weekend
```

```{r}
df = data.frame(rbind(java.week, 
                      java.weekend[rownames(java.weekend),]))

df$medida = c("java.week", "java.weekend")

df %>% 
  ggplot(aes(x = medida, ymin = X2.5., ymax = X97.5.)) + 
  geom_errorbar(width = .2)
```


```{r}
data %>%
  filter(file_extension == "py") %>%
  filter(!isWeekend) %>%
  bootstrap(median(users), R = 10000) %>% 
    CI.percentile(probs = c(.025, .975)) -> python.week
data %>%
  filter(file_extension == "py") %>%
  filter(isWeekend) %>%
  bootstrap(median(users), R = 10000) %>% 
    CI.percentile(probs = c(.025, .975)) -> python.weekend

cat(paste("Python on week days:\n"))
python.week
cat(paste("\n\nPython on weekend days:\n"))
python.weekend
```

```{r}
df = data.frame(rbind(python.week, 
                      python.weekend[rownames(python.week),]))
df$medida = c("python.week", "python.weekend")

df %>% 
  ggplot(aes(x = medida, ymin = X2.5., ymax = X97.5.)) + 
  geom_errorbar(width = .2)
```


```{r}
cat(paste("Java on weekend days:\n"))
java.weekend
cat(paste("\n\nPython on weekend days:\n"))
python.weekend
```

```{r}
df = data.frame(rbind(java.weekend, 
                      python.weekend[rownames(python.week),]))
df$medida = c("java.weekend", "python.weekend")

df %>% 
  ggplot(aes(x = medida, ymin = X2.5., ymax = X97.5.)) + 
  geom_errorbar(width = .2)
```
